# Generated by Django 4.2.13 on 2025-02-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fld_name', models.CharField(max_length=255)),
                ('Fld_specialization', models.CharField(max_length=255)),
                ('Fld_contact_number', models.CharField(max_length=20)),
                ('Fld_available_slots', models.JSONField()),
            ],
        ),
    ]
