# Generated by Django 4.2.13 on 2025-03-03 13:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_app', '0002_patient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patient',
            new_name='Tbl_Patient',
        ),
    ]
