# Generated by Django 4.2.13 on 2025-03-04 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_rename_patient_tbl_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fld_appointment_date', models.DateTimeField()),
                ('Fld_status', models.CharField(max_length=50)),
                ('Fld_slot', models.CharField(max_length=20)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.tbl_doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.tbl_patient')),
            ],
        ),
    ]
