# Generated by Django 4.2.13 on 2025-03-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_tbl_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_doctor',
            name='Fld_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
